Document: storagenode
Title: Debian storagenode Manual
Author: <insert document author here>
Abstract: This manual describes what storagenode is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/storagenode/storagenode.sgml.gz

Format: postscript
Files: /usr/share/doc/storagenode/storagenode.ps.gz

Format: text
Files: /usr/share/doc/storagenode/storagenode.text.gz

Format: HTML
Index: /usr/share/doc/storagenode/html/index.html
Files: /usr/share/doc/storagenode/html/*.html
