FROM nginx:latest
# maybe we should set version
COPY ./storagenode_amd64.zip /usr/share/nginx/html/storagenode_amd64.zip
COPY ./release/storagenode-updater_amd64.zip /usr/share/nginx/html/storagenode-updater_amd64.zip
RUN ls /usr/share/nginx/html

