FROM nginx:latest
# maybe we should set version
RUN apt update && apt install -y zip
RUN zip /usr/share/nginx/html/storagenode_linux_amd64 ./release/storagenode
RUN zip /usr/share/nginx/html/storagenode-updater_linux_amd64 ./release/storagenode-updater

